PyTraker/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from .views import SearchResultsView


app_name = 'PyTraker'
urlpatterns = [
    path('', views.home, name="home"),
    path('PyTraker/index', views.home, name="home"),
    path('PyTraker/sign_up/', views.sign_up, name="sign_up"),
    path('PyTraker/login', views.login_page, name="login"),
    path("PyTraker/logout", views.log_out, name="logout"),

    path("PyTraker/invoice/<int:project_id>/", views.invoice, name="invoice"),
    path("PyTraker/list_invoices/", views.invoice_list, name="list_invoices"),
    path("PyTraker/new_invoice/<int:project_id>/", views.new_invoice, name="new_invoice"),
    path("PyTraker/edit_invoice/<int:invoices_id>/", views.edit_invoice, name="edit_invoice"),
    path("PyTraker/delete_invoice/<int:invoice_id>/", views.delete_invoice, name="delete_invoice"),
    path("PyTraker/delete_invoice_conf/<int:invoice_id>/", views.delete_invoice_conf, name="delete_invoice_conf"),
    path("PyTraker/comments/<int:comment_id>/", views.comment_detail_view, name="comment_detail"),
    path("PyTraker/comments/", views.comment_create_view, name="comment-add"),
    path("PyTraker/comments/<int:comment_id>/delete/", views.comment_delete, name="comment_delete"),
    path("PyTraker/tasklist", views.tasklist, name="tasklist"),
    path("PyTraker/task_detail/<int:tasks_id>", views.task_detail, name="task_detail"),
    path("PyTraker/new_task", views.new_task, name="new_task"),
    path("PyTraker/edit_task/<int:tasks_id>", views.edit_task, name="edit_task"),
    path("PyTraker/change_status/<int:tasks_id>", views.change_status, name="change_status"),
    path("PyTraker/delete_task", views.delete_task, name="delete_task"),
    path("PyTraker/projects", views.projects, name="projects"),
    path("PyTraker/project_detail", views.project_detail, name="project_detail"),
    path("PyTraker/new_project", views.new_project, name="new_project"),
    path("PyTraker/edit_project/<int:pk>", views.edit_project, name="edit_project"),
    path("PyTraker/details_project/<int:pk>", views.details_project, name="details_project"),
    path("PyTraker/delete_project/<int:pk>", views.delete_project, name="delete_project"),
    path("PyTraker/delete_project_conf/<int:pk>", views.delete_project_conf, name="delete_project_conf"),
    path("PyTraker/list_projects", views.list_projects, name="list_projects"),
    path("PyTraker/workdiary", views.workdiary, name="workdiary"),
    path("PyTraker/workdiary_add", views.workdiary_add, name="workdiary_add"),
    path("PyTraker/workdiary_edit/<int:pk>", views.workdiary_edit, name="workdiary_edit"),
    path("PyTraker/workdiary_detail/<int:pk>", views.workdiary_details, name="workdiary_detail"),
    path("PyTraker/workdiary_delete/<int:pk>", views.workdiary_delete, name="workdiary_delete"),
    path("PyTraker/workdiary_conf_delete/<int:pk>", views.workdiary_conf_delete, name="workdiary_conf_delete"),

    path('search/', SearchResultsView.as_view(), name='search_results'),
    path("PyTraker/user_profile/<int:pk>", views.user_profile, name="user_profile"),
    path("PyTraker/user_profile_edit/<int:pk>", views.user_profile_edit, name="user_profile_edit"),

    # NoteBoard
    path('PyTraker/noteboard', views.noteboard),
    path('PyTraker/noteboard-create', views.noteboard_create),
    path('PyTraker/noteboard-update/<int:noteId>', views.noteboard_update),
    path('PyTraker/noteboard-delete/<int:noteId>', views.noteboard_delete)
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("PyTraker.urls")),
    path('PyTraker/', include('django.contrib.auth.urls'))
]

PyTraker/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(verbose_name="first name", max_length=50)
    lastname = models.CharField(verbose_name="last name", max_length=50)
    phonenumber = models.CharField(verbose_name="phone number", max_length=10)
    email = models.CharField(verbose_name="email", max_length=100)



class Clients(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Projects(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    clientID = models.ForeignKey(Clients, on_delete=models.CASCADE)
    payRate = models.IntegerField()
    startDate = models.DateTimeField()
    dueDate = models.DateTimeField()

    def __str__(self):
        return self.name


class Tasks(models.Model):
    projectID = models.ForeignKey(Projects, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    complete = models.BooleanField(default=False)
    due_date = models.DateTimeField()


    def __str__(self):
        return self.name


class Timers(models.Model):
    startTime = models.DateTimeField()
    endTime = models.DateTimeField()
    totaltime = models.CharField(max_length=100,default="0")
    totalhours = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    projectID = models.ForeignKey(Projects, on_delete=models.CASCADE,default='1')
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE, default='4')




class TaskNotes(models.Model):
    note = models.TextField(max_length=250)
    taskID = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.note


class ProjectNotes(models.Model):
    note = models.TextField(max_length=250)
    projectID = models.ForeignKey(Projects, on_delete=models.CASCADE)

    def __str__(self):
        return self.note


class Invoices(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    projectID = models.ForeignKey(Projects, on_delete=models.CASCADE)
    dateCreated = models.DateTimeField()
    dueDate = models.DateTimeField()

    def __str__(self):
        return self.projectID.name


class WorkDiary(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date = models.DateTimeField()
    projectID = models.ForeignKey(Projects, on_delete=models.CASCADE)
    projectNotes = models.CharField(max_length=2000, default='coming soon')
    taskID = models.ForeignKey(Tasks, on_delete=models.CASCADE)
    taskNotes = models.CharField(max_length=2000, default='coming soon')

class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=2000)
    comment_date = models.DateTimeField()
    workdiary = models.ForeignKey(WorkDiary, on_delete=models.CASCADE, default='1')


class Noteboard_Note(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    note = models.TextField()

PyTraker/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
#from django.template.defaulttags import register
from django import template
register = template.Library()


from django.db.models import Sum
from django.db.models import Avg


from .forms import UserForm, ProfileForm, CommentRawProduction, CommentForm, ProjectForm, InvoiceForm, WorkDiaryForm, \
    TaskForm
from .models import Invoices, Projects, Clients, Tasks, Timers, Comments, WorkDiary, Noteboard_Note


from .forms import UserForm, ProfileForm, CommentRawProduction, CommentForm, ProjectForm,TimerForm
from .models import Invoices, Projects, Clients, Tasks, Timers, Comments, Profile

from .forms import UserForm, ProfileForm, CommentRawProduction, CommentForm, ProjectForm
from .models import Invoices, Projects, Clients, Tasks, Timers, Comments, Profile, TaskNotes, ProjectNotes


# for import date and time
from _datetime import datetime
from django.utils import timezone
from django.template import defaultfilters
from django.utils.dateparse import parse_date
from django.views.generic import ListView
from django.db.models import Q, Sum




def home(request):
    mess = 'Welcome to our Work Tracking Application!'
    project_list = Projects.objects.all()
    paginator = Paginator(project_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # context = {'project_list': project_list}

    return render(request, 'PyTraker/index.html', {'page_obj': page_obj, 'mess': mess})


# return render(request, 'PyTraker/index.html')


def sign_up(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile_form = profile_form.save(commit=False)
            profile_form.user = user
            profile_form.save()
            userN = user_form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + userN)
            return redirect('/PyTraker/login/?next=/')
    else:
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
    return render(request, 'PyTraker/sign_up.html', {'user_form': user_form, 'profile_form': profile_form})


def login_page(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is None:
                login(request, user)
                return redirect('login')

        context = {}

        return render(request, 'PyTraker/login.html', context)


def log_out(request):
    if request.method == "POST":
        logout(request)

    mess = "Logged out succesfully!"
    return render(request, 'PyTraker/index.html', {'mess': mess})


# Invoice Views
@login_required
def invoice(request, project_id):
    # Get the invoice whose project id is the one being passed

    obj = Invoices.objects.get(projectID_id=project_id)
    #list of tasks
    tasks = Tasks.objects.filter(projectID_id=obj.projectID)
    #list of timers for the project
    timer = Timers.objects.filter(projectID_id=obj.projectID).values('task_id').annotate(tasktotal=Sum('totalhours'))
    #timersum = Timers.objects.filter(projectID_id=obj.projectID).values('task_id').aggregate(tasktotal=Sum('totalhours'))
    context = {
        'invoice_id': obj.id,
        'project_id': obj.projectID,
        'project_name': obj.projectID.name,
        'client_name': obj.projectID.clientID.name,
        'client_email': obj.projectID.clientID.email,
        'client_phone': obj.projectID.clientID.phone,
        'user_fname': obj.userID.first_name,
        'user_lname': obj.userID.last_name,
        'user_email': obj.userID.email,
        #'user_phone': obj.userID.phonenumber,
        'date_created': obj.dateCreated,
        'date_due': obj.dueDate,
        'hourly_rate': obj.projectID.payRate,
        'tasks_list': tasks,
        'timers': timer,
    }
    return render(request, "PyTraker/invoice.html", context)


@login_required
def invoice_list(request):
    all_invoices = Invoices.objects.order_by("-dateCreated")
    context = {"all_invoices": all_invoices}
    return render(request, "PyTraker/list_invoice.html", context)


@login_required
def new_invoice(request, project_id):
    # AUTO POPULATING THE FORM THE FIRST TIME AROUND
    # Get user information
    current_user = request.user
    userID = User.objects.get(id=current_user.id)

    # Get the project information
    project = Projects.objects.get(id=project_id)
    form = InvoiceForm(initial={
        'userID': userID,
        'projectID': project.id,
        'dateCreated': datetime.now(),
        'dueDate': ""
    })

    #Process form if is being sent by post
    if request.method == 'POST':
        filled_form = InvoiceForm(request.POST)
        if filled_form.is_valid():
            filled_form.save()
            note = "Invoice created!"
            return redirect('/PyTraker/details_project/'+str(project_id))
            #return render(request, 'PyTraker/new_invoice.html', {'note': note, 'form': form})
            #return redirect('PyTraker/details_project/'+str(project_id))

    return render(request, "PyTraker/new_invoice.html", {'form': form})


@login_required
def edit_invoice(request, invoices_id):
    invoice = Invoices.objects.get(pk=invoices_id)
    project_id =invoice.projectID.id
    form = InvoiceForm(instance=invoice)
    if request.method == "POST":
        populated_form = InvoiceForm(request.POST, instance=invoice)
        if populated_form.is_valid():
            populated_form.save()
            form = populated_form
            note = "Invoice has been updated."
            return redirect('/PyTraker/invoice/' + str(project_id))
            #return render(request, 'PyTraker/edit_invoice.html',
                          #{'note': note, 'invoice_form': form, 'invoice': invoice})
    else:
        return render(request, 'PyTraker/edit_invoice.html', {'invoice_form': form, 'invoice': invoice})


#Delete Invoice

@login_required
def delete_invoice(request, invoice_id):
    invoice = get_object_or_404(Invoices, pk=invoice_id)
    return render(request, 'PyTraker/delete_invoice.html', {'invoice': invoice})


@login_required
def delete_invoice_conf(request, invoice_id):
    invoice = int(invoice_id)
    del_invoice = Invoices.objects.get(id=invoice)
    project_id = del_invoice.projectID.id
    del_invoice.delete()
    return redirect('/PyTraker/details_project/' + str(project_id))


# comment page
@login_required
def comment_view(request):
    obj = Comments.objects.all()
    context = {
        'object': obj
    }
    return render(request, "PyTraker/comment_form.html", context)


@login_required
def comment_detail_view(request, comment_id):
    obj = Comments.objects.get(id=comment_id)
    context = {
        'comment': obj
    }
    return render(request, "PyTraker/comment_detail.html", context)


@login_required
def comment_create_view(request):
    if request.method == "POST":
        new_comment = CommentForm()
        current_user = request.user
        my_p = User.objects.get(id=current_user.id)
        new_comment.user = my_p
        new_comment.comment = request.POST.get('comment')
        # new_comment.comment_date = parse_date(request.POST.get('comment_date'))
        new_comment.comment_date = datetime.now()
        print(new_comment.user)
        print(new_comment.comment_date)
        print(new_comment.comment)
        Comments.objects.create(user=new_comment.user, comment=new_comment.comment,
                                comment_date=new_comment.comment_date)
    comments = Comments.objects.all()
    date = datetime.now()
    context = {
        'object': comments,
        'time': defaultfilters.date(date, "Y-m-d h:i A")
    }
    return render(request, "PyTraker/comment_form.html", context)


# Task Views
# list task
@login_required
def tasklist(request):
    all_task_list = Tasks.objects.filter(complete=False)
    context = {"all_task_list": all_task_list}
    return render(request, "PyTraker/tasklist.html", context)


# task detail
@login_required
def task_detail(request, tasks_id):
    tasks = get_object_or_404(Tasks, pk=tasks_id)
    return render(request, 'PyTraker/task_detail.html', {'tasks': tasks})


# create task
@login_required
def new_task(request):
    if request.method == 'POST':
        filled_form = TaskForm(request.POST or None)
        if filled_form.is_valid():
            created_task = filled_form.save()
            created_task_id = created_task.id
            note = 'Your new task: %s has been added.' % (filled_form.cleaned_data['name'])
            filled_form = TaskForm()
        else:
            created_task_id = None
            note = "Your task was not added, please try again."
        return render(request, 'PyTraker/new_task.html',
                      {'created_task_id': created_task_id, 'new_task': filled_form, 'note': note})
    else:
        form = TaskForm()
        return render(request, 'PyTraker/new_task.html', {'new_task': form})


# edit task
@login_required
def edit_task(request, tasks_id):
    task = Tasks.objects.get(pk=tasks_id)
    form = TaskForm(instance=task)
    if request.method == "POST":
        filled_form = TaskForm(request.POST, instance=task)
        if filled_form.is_valid():
            filled_form.save()

PyTraker/templates/PyTraker/comment_delete.html
{% extends "PyTraker/header.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete this comment?</h3>
    <input type="submit" value="Delete"/><a href="/PyTraker/workdiary">Cancel</a>
</form>
{% endblock %}

PyTraker/templates/PyTraker/comment_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
 <ul>
        <li><h2><a href="/PyTraker/comments/deatil/{{ comment.id }}">{{ comment.comment }}</a></h2></li>
        <li><p>{{ comment.user}}</p></li>
        <li><p>{{ comment.comment_date }}</p></li>
    </ul>

 <h3><a href="delete/" style="color:red">Delete</a></h3>
</body>
</html>

PyTraker/templates/PyTraker/header.html
<head>
    <title>PyTraker</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Sass/style.css' %}">
</head>
<body>
<header>
    <div class="logo-container">
        {% load static %}
        <div class="logo-img">
            <a href="/PyTraker/index"><img src="{% static "PyTraker/logo.png" %}" alt="My logo" id="logo"></a>
        </div>
        {% if user.is_authenticated %}
        <div class="search-wrapper">
           <form class="search-form" action="/search" method="get">
                <input name='q' type="text" placeholder="Search by Projects" aria-label="Search">
                <button class="new-btn" type="submit">Search</button>
           </form>
        </div>
            <div class="greetuser"><span>Hello, {{ request.user }}</span>  <a href="#" onClick="document.getElementById('logoutform').submit()"><button type="button" id="logout-btn">Logout</button></a></div>
            <form id="logoutform" method="POST"  action="{% url 'PyTraker:logout' %}">
            {% csrf_token %}
            <input type="hidden">
            </form>
        </div>
        {% else %}
        <div class="greetuser">
            <a href="{% url 'PyTraker:sign_up' %}" class="nav-link"  >Sign up</a>  <a href="/PyTraker/login/?next=/" class="nav-link" >Login</a>
        </div>
        {% endif %}
    </div>
<div class="nav-wrapper">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="/PyTraker/user_profile/{{ request.user.id }}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/PyTraker/workdiary">Work Diary</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/PyTraker/list_projects">List</a>
          <a class="dropdown-item" href="/PyTraker/new_project">Add New</a>
            <a class="dropdown-item" href="/PyTraker/list_invoices">Invoices</a>

        </div>
      </li>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tasks
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/PyTraker/tasklist">List</a>
          <a class="dropdown-item" href="/PyTraker/new_task">Add New</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/PyTraker/noteboard">Note Board</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>
</div>
</header>
<div class="container">
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
  $( function() {
    $( "#id_startDate" ).datepicker();
    $( "#id_dueDate" ).datepicker();
  } );
  </script>
<footer>PyTraker &#169; 2020 </footer>
 </body>

PyTraker/templates/PyTraker/noteboard_base.html
<head>
    <title>PyTraker</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'PyTraker/style.css' %}">
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/PyTraker/index">Home</a>
      </li>
        {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="/PyTraker/user_profile/{{ request.user.id }}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/PyTraker/workdiary">Work Diary</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/PyTraker/list_projects">List</a>
          <a class="dropdown-item" href="/PyTraker/new_project">Add New</a>
            <a class="dropdown-item" href="/PyTraker/list_invoices">Invoices</a>

        </div>
      </li>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tasks
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/PyTraker/tasklist">List</a>
          <a class="dropdown-item" href="/PyTraker/new_task">Add New</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/PyTraker/noteboard">Note Board</a>
      </li>
    </ul>

      <div class="nav-item">Hello, {{ request.user }} </div>  <a href="#" onClick="document.getElementById('logoutform').submit()"><button type="button" class="btn btn-dark" id="logout-btn">Logout</button></a>
<form id="logoutform" method="POST"  action="{% url 'PyTraker:logout' %}">
{% csrf_token %}
<input type="hidden">
</form>
{% else %}
<a href="{% url 'PyTraker:sign_up' %}" class="nav-link"  >Sign up</a>  <a href="/PyTraker/login/?next=/" class="nav-link" >Login</a>
{% endif %}
    <form class="form-inline my-2 my-lg-0" action="/search" method="get">
      <input class="form-control mr-sm-2"name='q' type="text" placeholder="Search by Projects" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</header>

<main>
    {% block content %} {% endblock %}
</main>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

 </body>

PyTraker/templates/PyTraker/noteboard_create.html
{% extends "PyTraker/header.html" %}

{% block content %}

<div class="container">

    <form method="POST" action="/PyTraker/noteboard-create"> {% csrf_token %}
        <div class="input-group nb-new">
          <div class="input-group-prepend">
            <span class="input-group-text">New Note</span>
          </div>
          <textarea name="newNoteText" class="form-control" aria-label="With textarea"
                    placeholder="Type here..." required autofocus></textarea>
        </div>

        <div class="row d-flex justify-content-center">
            <button type="submit" class="new-btn">Add Note</button>
            <a href="/PyTraker/noteboard" class="delete-btn">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

PyTraker/templates/PyTraker/project_detail.html
<p>Project: {{ projects.name }}</p>
<p>Description: {{ projects.description }}</p>
<p>Rate of Pay: {{ projects.payRate }}</p>
<p>Timeline: {{ projects.startDate }} - {{ projects.dueDate }}</p>

PyTraker/templates/PyTraker/user_profile_edit.html
{% extends "PyTraker/header.html" %}

{% block content %}
<div class="page-wrap">
<div class="container">
        <div class="card">
            <h5 class="card-header">Edit Profile</h5>
            <div class="card-body">
                <form action="/PyTraker/user_profile_edit/{{ user.id }}" method="post">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ user_profile_edit.as_p }}
                    <input type="submit" value="Confirm" class="new-btn">
                    <a href="/PyTraker/user_profile/{{ user.id }}" class="delete-btn" >Cancel</a>
                </form>
            </div>
        </div>
</div>

{% endblock %}
</div>